apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: jenkins-role-bindings-oc4
message: |-
  When using a Jenkins Build Pipeline, this template will bless the following to enable your pipeline strategy:
    * bless the dev/test/prod default user with image-puller access in Tools
    * bless the tools Jenkins user with view access in dev/test/prod
metadata:
  annotations:
    openshift.io/display-name: Jenkins Role Bindings
    description: |-
      This is a template for OpenShift Jenkins Pipelines.
    iconClass: icon-jenkins
    tags: instant-app,jenkins
  name: jenkins-role-bindings
parameters:
- displayName: Openshift Namespace License Plate (ex// pjztlm)
  name: LICENSE_PLATE
  required: true

objects:
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    name: jenkins_view
    namespace: "${LICENSE_PLATE}-dev"
  subjects:
    - kind: ServiceAccount
      name: jenkins
      namespace: "${LICENSE_PLATE}-tools"
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: view

- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    name: jenkins_view
    namespace: "${LICENSE_PLATE}-test"
  subjects:
    - kind: ServiceAccount
      name: jenkins
      namespace: "${LICENSE_PLATE}-tools"
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: view

- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    name: jenkins_view
    namespace: "${LICENSE_PLATE}-prod"
  subjects:
    - kind: ServiceAccount
      name: jenkins
      namespace: "${LICENSE_PLATE}-tools"
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: view

- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    name: DEV-default-image-puller
    namespace: "${LICENSE_PLATE}-tools"
  subjects:
    - kind: ServiceAccount
      name: default
      namespace: "${LICENSE_PLATE}-dev"
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: 'system:image-puller'

- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    name: TEST-default-image-puller
    namespace: "${LICENSE_PLATE}-tools"
  subjects:
    - kind: ServiceAccount
      name: default
      namespace: "${LICENSE_PLATE}-test"
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: 'system:image-puller'

- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    name: PROD-default-image-puller
    namespace: "${LICENSE_PLATE}-tools"
  subjects:
    - kind: ServiceAccount
      name: default
      namespace: "${LICENSE_PLATE}-prod"
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: 'system:image-puller'

- apiVersion: security.devops.gov.bc.ca/v1alpha1
  kind: NetworkSecurityPolicy
  metadata:
    name: egress-policy
    namespace: ${LICENSE_PLATE}-tools
  spec:
    description: allow ${LICENSE_PLATE}-tools namespace to talk to the internet.
    destination:
      - - 'ext:network=any'
    source:
      - - $namespace=${LICENSE_PLATE}-tools

- apiVersion: security.devops.gov.bc.ca/v1alpha1
  kind: NetworkSecurityPolicy
  metadata:
    name: egress-policy
    namespace: ${LICENSE_PLATE}-dev
  spec:
    description: allow ${LICENSE_PLATE}-dev namespace to talk to the internet.
    destination:
      - - 'ext:network=any'
    source:
      - - $namespace=${LICENSE_PLATE}-dev

- apiVersion: security.devops.gov.bc.ca/v1alpha1
  kind: NetworkSecurityPolicy
  metadata:
    name: egress-policy
    namespace: ${LICENSE_PLATE}-test
  spec:
    description: allow ${LICENSE_PLATE}-test namespace to talk to the internet.
    destination:
      - - 'ext:network=any'
    source:
      - - $namespace=${LICENSE_PLATE}-test

- apiVersion: security.devops.gov.bc.ca/v1alpha1
  kind: NetworkSecurityPolicy
  metadata:
    name: egress-policy
    namespace: ${LICENSE_PLATE}-prod
  spec:
    description: allow ${LICENSE_PLATE}-prod namespace to talk to the internet.
    destination:
      - - 'ext:network=any'
    source:
      - - $namespace=${LICENSE_PLATE}-prod

- apiVersion: security.devops.gov.bc.ca/v1alpha1
  kind: NetworkSecurityPolicy
  metadata:
    name: int-cluster-k8s-api-comms
    namespace: ${LICENSE_PLATE}-tools
  spec:
    description: allow ${LICENSE_PLATE}-tools pods to talk to the k8s api
    destination:
      - - 'int:network=internal-cluster-api-endpoint'
    source:
      - - $namespace=${LICENSE_PLATE}-tools

- apiVersion: security.devops.gov.bc.ca/v1alpha1
  kind: NetworkSecurityPolicy
  metadata:
    name: int-cluster-k8s-api-comms
    namespace: ${LICENSE_PLATE}-dev
  spec:
    description: allow ${LICENSE_PLATE}-dev pods to talk to the k8s api
    destination:
      - - 'int:network=internal-cluster-api-endpoint'
    source:
      - - $namespace=${LICENSE_PLATE}-dev

- apiVersion: security.devops.gov.bc.ca/v1alpha1
  kind: NetworkSecurityPolicy
  metadata:
    name: int-cluster-k8s-api-comms
    namespace: ${LICENSE_PLATE}-test
  spec:
    description: allow ${LICENSE_PLATE}-test pods to talk to the k8s api
    destination:
      - - 'int:network=internal-cluster-api-endpoint'
    source:
      - - $namespace=${LICENSE_PLATE}-test

- apiVersion: security.devops.gov.bc.ca/v1alpha1
  kind: NetworkSecurityPolicy
  metadata:
    name: int-cluster-k8s-api-comms
    namespace: ${LICENSE_PLATE}-prod
  spec:
    description: allow ${LICENSE_PLATE}-prod pods to talk to the k8s api
    destination:
      - - 'int:network=internal-cluster-api-endpoint'
    source:
      - - $namespace=${LICENSE_PLATE}-prod

- apiVersion: security.devops.gov.bc.ca/v1alpha1
  kind: NetworkSecurityPolicy
  metadata:
    name: intra-namespace-comms
    namespace: ${LICENSE_PLATE}-tools
  spec:
    description: allow ${LICENSE_PLATE}-tools namespace to talk to itself
    destination:
      - - $namespace=${LICENSE_PLATE}-tools
      - - $namespace=${LICENSE_PLATE}-dev
      - - $namespace=${LICENSE_PLATE}-test
      - - $namespace=${LICENSE_PLATE}-prod
    source:
      - - $namespace=${LICENSE_PLATE}-tools

- apiVersion: security.devops.gov.bc.ca/v1alpha1
  kind: NetworkSecurityPolicy
  metadata:
    name: intra-namespace-comms
    namespace: ${LICENSE_PLATE}-dev
  spec:
    description: allow ${LICENSE_PLATE}-dev namespace to talk to itself and tools
    destination:
      - - $namespace=${LICENSE_PLATE}-tools
      - - $namespace=${LICENSE_PLATE}-dev
    source:
      - - $namespace=${LICENSE_PLATE}-dev

- apiVersion: security.devops.gov.bc.ca/v1alpha1
  kind: NetworkSecurityPolicy
  metadata:
    name: intra-namespace-comms
    namespace: ${LICENSE_PLATE}-tools
  spec:
    description: allow ${LICENSE_PLATE}-test namespace to talk to itself and tools
    destination:
      - - $namespace=${LICENSE_PLATE}-tools
      - - $namespace=${LICENSE_PLATE}-test
    source:
      - - $namespace=${LICENSE_PLATE}-test

- apiVersion: security.devops.gov.bc.ca/v1alpha1
  kind: NetworkSecurityPolicy
  metadata:
    name: intra-namespace-comms
    namespace: ${LICENSE_PLATE}-tools
  spec:
    description: allow ${LICENSE_PLATE}-prod namespace to talk to itself and tools
    destination:
      - - $namespace=${LICENSE_PLATE}-tools
      - - $namespace=${LICENSE_PLATE}-prod
    source:
      - - $namespace=${LICENSE_PLATE}-prod
