kind: Template
apiVersion: v1
metadata:
  name: meta-deployment-config-template
parameters:
  - name: appName
    displayName: Name
    description: A prefix appended to all objects
    required: true
  - name: TAG
    required: true
    value: dev
  - name: GIT_REPO
    required: true
    value: https://github.com/ChrisHoban/ssg-openshift-meta-templates.git
  - name: namespace
    required: true
  - name: container_port
    value: '8080'
objects:
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      annotations:
      creationTimestamp: null
      labels:
        app: ${appName}
      name: ${appName}
    spec:
      replicas: 2
      selector:
        io.kompose.service: ${appName}
      strategy:
        resources: {}
      template:
        metadata:
          creationTimestamp:
          labels:
            io.kompose.service: ${appName}
        spec:
          containers:
          - image: ''
            name: ${appName}
            ports:
            - containerPort: ${container_port}
            resources: {}
          restartPolicy: Always
      test: false
      triggers:
      - type: ConfigChange
      - imageChangeParams:
          automatic: true
          containerNames:
          - ${appName}
          from:
            kind: ImageStreamTag
            name: ${appName}:${TAG}
            namespace: ${namespace}
        type: ImageChange
    status: {}
