apiVersion: v1
kind: Service
parameters:
- description: The name assigned to all of the frontend objects defined in this template.
  displayName: Name
  name: appName
  required: true
- description: The name of the port to be referenced by a route
  displayName: Name
  name: portName
  required: true
  value: web
- description: The port used for external access
  displayName: External Port
  name: sourcePort
  required: true
  value: 80
- description: The port the internal running service exposes.
  displayName: Internal Port
  name: targetPort
  required: true
  value: 8080
metadata:
  name: ${appName}
  labels:
    app: ${appName}
    template: ${appName}
  annotations:
    description: Exposes and load balances the application pods
spec:
  ports:
    - name: ${portName}
      port: ${sourcePort}
      targetPort: ${targetPort}
    selector:
      deploymentconfig: ${appName}
