kind: Template
apiVersion: v1
metadata:
  name: meta-deployment-config-template
parameters:
- description: The name of the route and matching service
  displayName: Name
  name: appName
  required: true
- description: This namespace (used in hostname)
  displayName: Name
  name: namespace
  required: true
- description: The name of the port to be referenced by a route
  displayName: Name
  name: portName
  required: true
  value: web
objects:
- apiVersion: v1
  kind: Route
  metadata:
    name: ${appName}
    labels:
      template: master-build-pipeline
      app: ${appName}
  spec:
    host: ${appName}-${namespace}.pathfinder.gov.bc.ca
    to:
      kind: Service
      name: ${appName}
