apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: imagestream
message: |-
  This will create a standard imagestream
metadata:
  annotations:
    openshift.io/display-name: Imagestream Template
    description: |-
      This will create a standard imagestream
    iconClass: icon-openshift
    tags: instant-app
  name: imagestream-template
  labels:
    appcluster: nextcloud
parameters:
  - description: The OpenShift Namespace where the ImageStreams reside.
    displayName: Namespace (ie <prefix>-tools, <prefix>-dev etc)
    name: namespace
    required: true
    value:
  - description: The name of the resulting Imagestream
    displayName: Imagestream Name
    name: imagestreamName
    required: true
    value:
objects:
  - apiVersion: v1
    kind: ImageStream
    metadata:
      labels:
        application: ${imagestreamName}
        appcluster: nextcloud
      name: ${imagestreamName}
      namespace: "${namespace}"
    spec:
      lookupPolicy:
        local: true
