kind: Template
apiVersion: v1
metadata:
  name: nextcloud
  annotations:
    description: "Nextcloud Builder - takes a source dockerimage and dockerfile to create a custom container"
    tags: "fileshare,nextcloud"
    iconClass: fa-cloud-upload
    template.openshift.io/provider-display-name: "ChrisHoban"
    template.openshift.io/documentation-url: "https://github.com/ChrisHoban/ssg-openshift-meta-templates/blob/master/openshift/oc4-meta-templates/services/nextcloud/README.md"
    template.openshift.io/support-url: "https://github.com/ChrisHoban/ssg-openshift-meta-templates/issues"
parameters:
- name: MY_NEXTCLOUD_DOCKERFILE_REPO
  description: Nginx Dockerfile source repository
  value: https://github.com/ChrisHoban/ssg-openshift-meta-templates.git
- name: MY_NEXTCLOUD_DOCKERFILE_REPO_REF
  description: Nginx Dockerfile source repository branch / tags
  value: master
- name: MY_NEXTCLOUD_CONTEXT_DIR
  description: Nextcloud Context Directory
  value: openshift/oc4-meta-templates/services/nextcloud/nginx
- name: namespace
  description: Namespace containing nextcloud imagestreams
  value:
- name: outputImageName
  description: output imagestream
objects:
- kind: BuildConfig
  apiVersion: v1
  namespace: {namespace}
  metadata:
    creationTimestamp: null
    labels:
      build: my-nginx
      app: nextcloud
      appcluster: nextcloud
    name: my-nginx
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: ${outputImageName}:latest
        namespace: ${namespace}
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      git:
        uri: ${MY_NEXTCLOUD_DOCKERFILE_REPO}
        ref: ${MY_NEXTCLOUD_DOCKERFILE_REPO_REF}
      type: Git
      contextDir: ${MY_NEXTCLOUD_CONTEXT_DIR}
    strategy:
      dockerStrategy:
        imageOptimizationPolicy: SkipLayers
        from:
          kind: ImageStreamTag
          name: nginx:latest
      type: Docker
    triggers:
    - type: ConfigChange
